// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1770992898);
user_pref("app.update.lastUpdateTime.background-update-timer", 1770992898);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1770992898);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1770992864);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.startup.homepage_override.buildID", "20260106170501");
user_pref("browser.startup.homepage_override.mstone", "140.7.0");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.lastAppBuildId", "20260207192345");
user_pref("extensions.lastAppVersion", "8.0.3");
user_pref("extensions.lastPlatformVersion", "140.7.0");
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.zotero.dataDir", "/home/lgp/Zotero");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.ignoreLegacyDataDir.auto", true);
user_pref("extensions.zotero.import.createCollection", true);
user_pref("extensions.zotero.import.createNewCollection.fromFileOpenHandler", false);
user_pref("extensions.zotero.import.fileHandling", "link");
user_pref("extensions.zotero.lastSelectedPrefPane", "zotero-prefpane-general");
user_pref("extensions.zotero.lastViewedFolder", "L1");
user_pref("extensions.zotero.newItemTypeMRU", "document,newspaperArticle");
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"true\"},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-splitter\":{\"state\":\"\",\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"width\":\"513\",\"height\":\"205\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-splitter-stacked\":{\"state\":\"collapsed\"}}");
user_pref("extensions.zotero.panes.abstract.open", true);
user_pref("extensions.zotero.panes.attachment-annotations.open", true);
user_pref("extensions.zotero.panes.attachment-info.open", true);
user_pref("extensions.zotero.panes.attachments.open", true);
user_pref("extensions.zotero.panes.context-all-notes.open", true);
user_pref("extensions.zotero.panes.context-item-notes.open", true);
user_pref("extensions.zotero.panes.info.open", true);
user_pref("extensions.zotero.panes.libraries-collections.open", true);
user_pref("extensions.zotero.panes.note-info.open", true);
user_pref("extensions.zotero.panes.notes.open", true);
user_pref("extensions.zotero.panes.related.open", true);
user_pref("extensions.zotero.panes.tags.open", true);
user_pref("extensions.zotero.postUpgradeBannerVersionShown", 8);
user_pref("extensions.zotero.prefVersion", 20);
user_pref("extensions.zotero.sidebarState", "{\"library\":{\"width\":240,\"open\":false},\"reader\":{\"width\":240,\"open\":false},\"note\":{\"width\":240,\"open\":false}}");
user_pref("extensions.zotero.sourceList.persist", "{\"L1\":true,\"P1\":false}");
user_pref("extensions.zotero.sync.autoSync", false);
user_pref("extensions.zotero.sync.fulltext.enabled", false);
user_pref("extensions.zotero.sync.reminder.autoSync.lastDisplayed", 1770993821);
user_pref("extensions.zotero.sync.reminder.setUp.enabled", false);
user_pref("extensions.zotero.sync.reminder.setUp.lastDisplayed", 1770993067);
user_pref("extensions.zotero.sync.server.username", "fromKansasCity");
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zoteroOpenOfficeIntegration.lastAttemptedVersion", "7.0.6.SOURCE");
user_pref("extensions.zoteroOpenOfficeIntegration.skipInstallation", true);
user_pref("extensions.zoteroOpenOfficeIntegration.unopkgPaths", "{\"/usr/bin/unopkg\":true,\"/usr/lib/libreoffice/program/unopkg\":true}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("intl.accept_languages", "zh-CN, zh, zh-TW, zh-HK, en-US, en");
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
